module.exports = () => `С помощью оператора <code>throw</code> мы можем создавать собственные ошибки. С этим оператором вы можете генерировать исключения. Исключением может быть <b>строка</b>, <b>число</b>, <b>логическое значение</b> или <b>объект</b>. В этом случае нашим исключением является строка <code>'Hello world'</code>.

С помощью оператора <code>catch</code> мы можем указать, что делать, если в блоке<code> try</code> выдается исключение. Исключение: строка <code>'Hello world'</code>. <code>e</code> теперь равно той строке, которую мы записываем. Это приводит к <code>'Oh error: Hello world'</code>.
`;